### ISSUE TITLE
Stretchy Header

### ISSUE THREAD

**Issue by osmanyildirim** [mattga/MGCollapsingHeader#10]
Hello,

How can I make an Stretchy Header as following example ?

[https://i.pinimg.com/originals/cb/93/d5/cb93d56cc0272831600c47518b9cd1ab.gif](https://i.pinimg.com/originals/cb/93/d5/cb93d56cc0272831600c47518b9cd1ab.gif)

**Comment by yildirimosman** [comment]
@mattga ?

**Comment by mattga** [comment]
You should be able to get this header behaving like your example by
setting it up as instructed and setting the imageview's content mode to
Aspect Fill. The image will then adjust like in this gif when scroll view
is pulled down. Unfortunately the library has some issues with later
versions of iOS that I have yet to fix. If it is not working for you with
iOS 9+, let me know what issues you're having and I can try to help.

**Comment by Nitinbond** [comment]
Hello Adn,
Can i stop rapping of table view while scrolling my  table, Actually i want only scroll HeaderView Not hiding the table view cell while scrolling.

**Comment by Nitinbond** [comment]
how manage circular image view inside of Header?
![screen shot 2018-03-24 at 7 54 49 pm](https://user-images.githubusercontent.com/11436995/37865094-86771f7c-2f9d-11e8-9aed-d8befb7aa171.png)
![screen shot 2018-03-24 at 7 54 37 pm](https://user-images.githubusercontent.com/11436995/37865095-86cf5dd6-2f9d-11e8-89d8-2fa33e2e4b16.png)
![screen shot 2018-03-24 at 7 54 13 pm](https://user-images.githubusercontent.com/11436995/37865096-87189384-2f9d-11e8-9b19-395c0115081f.png)

**Comment by Nitinbond** [comment]
Also help me yo design like this ⇣
![img_20180322_144059 966](https://user-images.githubusercontent.com/11436995/37865119-cecc7bc8-2f9d-11e8-95bb-de86460ab9c4.png)
![img_20180322_144134 823](https://user-images.githubusercontent.com/11436995/37865120-cf36fe8a-2f9d-11e8-8273-85120bb666d1.jpg)

**Comment by mattga** [comment]
I assume you want the small image to be circular in the collapsed view, and then slide to the center while increasing in radius. So there are five things that need to be animated as the view collapses: radius, x position, y position, width, height. Just calculate the correct change in those attributes. For example:

```
double radiusChange = -22.0;
attrs = @[
    [MGTransform transformAttribute:MGAttributeX byValue:-120],
    [MGTransform transformAttribute:MGAttributeY byValue:-2],
    [MGTransform transformAttribute:MGAttributeWidth byValue:2 * radiusChange],
    [MGTransform transformAttribute:MGAttributeHeight byValue:2 * radiusChange],
    [MGTransform transformAttribute:MGAttributeCornerRadius byValue:radiusChange],
    [MGTransform transformAttribute:MGAttributeFontSize byValue:-8.0]
];
```

<img width="378" alt="screen shot 2018-03-24 at 10 50 44 am" src="https://user-images.githubusercontent.com/2767482/37865925-4a256dea-2f51-11e8-9af3-7818cd9f6a46.png">
<img width="376" alt="screen shot 2018-03-24 at 10 50 56 am" src="https://user-images.githubusercontent.com/2767482/37865926-4a356b8c-2f51-11e8-9f98-e60900a2056b.png">
<img width="377" alt="screen shot 2018-03-24 at 10 51 03 am" src="https://user-images.githubusercontent.com/2767482/37865927-4a451032-2f51-11e8-9f56-8e820857dfe1.png">

**Comment by Nitinbond** [comment]
And what about table row hidden start of scrolling, i want scrolls in only headerview don’t hide table cell

Sent from my iPhone

On 24-Mar-2018, at 9:21 PM, Matthew Gardner <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume you want the small image to be circular in the collapsed view, and then slide to the center while increasing in radius. So there are five things that need to be animated as the view collapses: radius, x position, y position, width, height. Just calculate the correct change in those attributes. For example:

double dr = -22.0; attrs = @[ [MGTransform transformAttribute:MGAttributeX byValue:-120], [MGTransform transformAttribute:MGAttributeY byValue:-2], [MGTransform transformAttribute:MGAttributeWidth byValue:2 * dr], [MGTransform transformAttribute:MGAttributeHeight byValue:2 * dr], [MGTransform transformAttribute:MGAttributeCornerRadius byValue:dr], [MGTransform transformAttribute:MGAttributeFontSize byValue:-8.0] ];

[screen shot 2018-03-24 at 10 50 44 am]<https://user-images.githubusercontent.com/2767482/37865925-4a256dea-2f51-11e8-9af3-7818cd9f6a46.png>

[screen shot 2018-03-24 at 10 50 56 am]<https://user-images.githubusercontent.com/2767482/37865926-4a356b8c-2f51-11e8-9f98-e60900a2056b.png>

[screen shot 2018-03-24 at 10 51 03 am]<https://user-images.githubusercontent.com/2767482/37865927-4a451032-2f51-11e8-9f56-8e820857dfe1.png>

**Comment by mattga** [comment]
Sorry but this us currently how the library works. I intend improve it in the way you mention but unfortunately do not have time.

**Comment by Nitinbond** [comment]
it's ok i'll wait for that.
