### ISSUE TITLE
tableview or collectionview contentInset.bottom should be automatically updated

### ISSUE THREAD

**Issue by Jackson0111** [mattga/MGCollapsingHeader#4]
Great work! It's really easy to use. But I noticed something that was not implemented. When the scrollview (either table view or collection view)'s bounds is smaller than (self.view.frame.height - minimum header height), there is a UI bug. It looks like the scrollview and header view are fighting over the bottom constraint. Not sure if this could be fixed in storyboard, but here's how i fix it: 

```
        if (collectionviewContentHeight > self.collectionView.frame.height) && (collectionviewContentHeight < (self.view.frame.height - 50)) { // only change bottom inset when needed
            self.collectionView.contentInset.bottom = (self.view.frame.height - 50) - collectionviewContentHeight
        }
```

Let me know if there could be a better way to do so. :)

**Comment by mattga** [comment]
Thank you Jackson! Can you show me the auto layout constraints you are using? My initial thought is this is an issue with the constraints, but they could very well be valid. The idea behind this implementation is that if constraints are setup perfectly, changing the value of one should dynamically adjust all other constraints without any "fighting" between them (as as the idea behind auto layout). I'm eager to find any singularities to this idea, so thank you for finding this bug!

**Comment by Jackson0111** [comment]
Not sure how to show you the layout constraints, so I just took a screenshot. Here:
![screen shot 2016-06-25 at 11 52 22 am](https://cloud.githubusercontent.com/assets/13260808/16357680/556763e2-3acb-11e6-897f-2a84d1c54392.png)

And basically I have a header view and a collection view, and I set auto layout just like your example project.

**Comment by mattga** [comment]
Ya that looks good. How about the constraints for the Header view?

**Comment by Jackson0111** [comment]
The screenshot shows all the constraints I have, for the collection view as well as the header view.

**Comment by mattga** [comment]
The header view should also have some constraints under it which include
constraints between itself and it's subviews. In particular there should be
a constraint for the height of the header that shows up under Header view
as opposed to under the top level View.

**Comment by Jackson0111** [comment]
Yes. Sorry, here's all the constraints I have: 
![screen shot 2016-06-26 at 11 27 28 am](https://cloud.githubusercontent.com/assets/13260808/16363197/fdd9c3b0-3b90-11e6-95be-b7cc14b663c3.png)

**Comment by mattga** [comment]
Ah I see now. It is only with collection view it appears. Thanks again! I'll patch it in the next release.

**Comment by Jackson0111** [comment]
Great work!

**Comment by mattga** [comment]
New release handles this case (but breaks old code). Let me know if there's any issues.
