### ISSUE TITLE
not working on Xcode 8 because constraint differences

### ISSUE THREAD

**Issue by osmanyildirim** [mattga/MGCollapsingHeader#7]
I have upgraded the project I developed with Xcode 7 to Xcode 8.I also **did not use Auto Layout** because the application works on a **single device model**, and compared it to a problem in this.Now my question is: This library was acting on constraints with **Xcode 7,** the old project was added as a **default constraint**, but I see that **Xcode 8** does not have a default constraint. I got this in the following way

With Xcode 7 I get the following result when I write console. _po button.constraints_

`-[0] : NSContentSizeLayoutConstraint:0x7f93916b1210 H:[UIButton:0x7f9391615b20'Button'(46)] Hug:250 CompressionResistance:750`
`-[1] : NSContentSizeLayoutConstraint:0x7f93916141b0 V:[UIButton:0x7f9391615b20'Button'(30)] Hug:250 CompressionResistance:750`

With **Xcode 8** I get the following result when I write console. _po button.constraints_

`0 elements`

As I said, I did not add the related **button constraint** in both projects, but by default in Xcode 7 there are **2 NSContentSizeLayoutConstraints** visible. In Xcode 8, **no NSContentSizeLayoutConstraint** appears

Do you know why and how to solve it?

**Comment by osmanyildirim** [comment]
Do you have any idea?

**Comment by mattga** [comment]
What version are you using? The latest version does not add constraints by default, you have to add them yourself. In the older it attempts to find the appropriate constraints, but this was buggy.
