### ISSUE TITLE
The Demo Project doesn't work anymore

### ISSUE THREAD

**Issue by albert0m** [mattga/MGCollapsingHeader#9]
The errors are:

No visible @interface for 'MGCollapsingHeaderView' declares the selector 'setCollapsingConstraint:'

No known class method for selector 'transformAttribute:byValue:'

No visible @interface for 'MGCollapsingHeaderView' declares the selector 'collapseWithScroll:'

Did you change the logic of the library? Xcode 8.2.1

**Comment by mattga** [comment]
The demo works for me (there might be an issue with the podspec). I will
try and resolve this and other issues this weekend as I haven't touched the library for months.
Sorry about the inactivity.

**Comment by albert0m** [comment]
sorry, my mistake. I tested it on a clean install and it works just fine. Thank you anyways!
